// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDiU7CW_0RiFJszy1xs3TybdVpI553ms8',
    appId: '1:683431064020:web:3446002f4b0489698ea641',
    messagingSenderId: '683431064020',
    projectId: 'digital-business-card-ea8cf',
    authDomain: 'digital-business-card-ea8cf.firebaseapp.com',
    storageBucket: 'digital-business-card-ea8cf.firebasestorage.app',
    measurementId: 'G-1R4TPKCSQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBi1p-1Nd1hmVqzKD6t7XWaasCiyftjsI4',
    appId: '1:683431064020:android:9a97f7562c207f7e8ea641',
    messagingSenderId: '683431064020',
    projectId: 'digital-business-card-ea8cf',
    storageBucket: 'digital-business-card-ea8cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPWn6BZ0lGmOpCntFFULxKR3PT1T7Z0IA',
    appId: '1:683431064020:ios:d88e4cd5bb05ba878ea641',
    messagingSenderId: '683431064020',
    projectId: 'digital-business-card-ea8cf',
    storageBucket: 'digital-business-card-ea8cf.firebasestorage.app',
    iosBundleId: 'com.example.digitalBusinessCard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPWn6BZ0lGmOpCntFFULxKR3PT1T7Z0IA',
    appId: '1:683431064020:ios:d88e4cd5bb05ba878ea641',
    messagingSenderId: '683431064020',
    projectId: 'digital-business-card-ea8cf',
    storageBucket: 'digital-business-card-ea8cf.firebasestorage.app',
    iosBundleId: 'com.example.digitalBusinessCard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDiU7CW_0RiFJszy1xs3TybdVpI553ms8',
    appId: '1:683431064020:web:67d530f26730f56d8ea641',
    messagingSenderId: '683431064020',
    projectId: 'digital-business-card-ea8cf',
    authDomain: 'digital-business-card-ea8cf.firebaseapp.com',
    storageBucket: 'digital-business-card-ea8cf.firebasestorage.app',
    measurementId: 'G-3VC9S31EKY',
  );
}
